[package]
name = "ember"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"
license = "MIT OR Apache-2.0"
description = "Safe low-level Vulkan bindings"

[dependencies]
# TODO: Feature
raw-window-handle = "0.4"

[workspace]
members = ["demo"]
