[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
ember = {path = "..", features = ["window"]}
winit = "0.26"
byte-strings = "0.2"
anyhow = {version = "1.0", features = ["backtrace"]}
