[package]
name = "hello-triangle"
version = "0.1.0"
edition = "2021"

[dependencies]
maia = { path = "..", features = [ "window" ] }
winit = "0.26"
bytemuck = { version = "1.0" }
inline-spirv = "0.1"
